[package]
name = "u5-tui"
version.workspace = true
edition.workspace = true

[features]
default = []
visual = ["dep:u5-bevy"]

[dependencies]
u5-runtime = { workspace = true }
u5-bevy = { workspace = true, optional = true }
image = { workspace = true }

[lib]
name = "u5_tui"
path = "src/lib.rs"

[[bin]]
name = "u5-engine"
path = "src/main.rs"
